site:
  title: The Internals Of Apache Spark
  url: https://books.japila.pl/apache-spark-internals
  start_page: apache-spark-internals::index.adoc
  keys:
    google_analytics: 'UA-86782445-1'
  robots: allow
content:
  sources:
    - url: https://github.com/japila-books/apache-spark-internals.git
      branches: master
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    sectlinks: ''
    linkattrs: ''
    spark-version: '2.4.5'
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
  - path: .nojekyll
  - path: ui.yml
    contents: "static_files: [ .nojekyll ]"
output:
  dir: .out/github-pages
runtime:
  cache_dir: .out/cache
  fetch: true
